export interface Trip {
  id: number
  title: string
  description: string
  image: string
  price: string
  originalPrice?: string
  duration: string
  difficulty: string
  groupSize: string
  rating: number
  reviews: number
  slug: string
  highlights: string[]
  location: string
  category: "one-day" | "two-day"
  detailedDescription: string
  itinerary: {
    day?: number
    time?: string
    title?: string
    activity?: string
    activities?: string[]
    meals?: string[]
  }[]
  included: string[]
  excluded: string[]
  gallery: string[]
  faqs: {
    question: string
    answer: string
  }[]
  pickupPoints: string[]
  cancellationPolicy: string
  thingsToCarry: string[]
}

export const allTrips: Trip[] = [
  // One Day Trips
  {
    id: 1,
    title: "Nandi Hills Sunrise Trek",
    description:
      "Wake up to an unforgettable adventure! The Nandi Hills Sunrise Trek is one of the most sought-after quick getaways from Bangalore – perfect for beginners, nature lovers, and anyone craving fresh mountain air and mesmerizing sunrise views.",
    detailedDescription:
      "Wake up to an unforgettable adventure! The Nandi Hills Sunrise Trek is one of the most sought-after quick getaways from Bangalore – perfect for beginners, nature lovers, and anyone craving fresh mountain air and mesmerizing sunrise views. This iconic hill fort offers breathtaking panoramic vistas, ancient temples, and is accessible to trekkers of all experience levels.",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Nandi%20Hills%20One%20Day%20Trek.jpg-Tr34J8kEhyCUFRg6i5gKaJ1Vze0njR.jpeg",
    price: "₹799",
    originalPrice: "₹999",
    duration: "1 Day",
    difficulty: "Easy",
    groupSize: "15-25",
    rating: 4.7,
    reviews: 89,
    slug: "nandi-hills-sunrise-trek",
    highlights: [
      "Ideal for all trekkers - Beginners to seasoned hikers",
      "Ancient hill fort trail with scenic viewpoints",
      "Budget-friendly adventure",
      "Mesmerizing sunrise views over the landscape",
    ],
    location: "60km from Bangalore",
    category: "one-day",
    itinerary: [
      { time: "Day 0", activity: "Departure from Bengaluru at selected pickup points" },
      { time: "11:15 PM", activity: "Gopalan Arcade, RR Nagar" },
      { time: "11:30 PM", activity: "Kathriguppe Circle, Kathriguppe" },
      { time: "11:45 PM", activity: "BMTC Bus Stop, Banashankari" },
      { time: "12:05 AM", activity: "Udupi Garden Signal, BTM Layout" },
      { time: "12:15 AM", activity: "Bus Stop, Silk Board" },
      { time: "12:45 AM", activity: "Shell Petrol Pump, Bellandur" },
      { time: "01:15 AM", activity: "Opp. Kalamandir, Marathahalli" },
      { time: "01:35 AM", activity: "HP Petrol Pump, Tin Factory" },
      { time: "01:45 AM", activity: "Opp. Esteem Mall, Hebbal" },
      { time: "02:00 AM", activity: "Reach Nandi base, rest or stargaze" },
      { time: "03:30 AM", activity: "Start trek after orientation" },
      { time: "05:30 AM", activity: "Reach summit & enjoy the sunrise" },
      { time: "07:00 AM", activity: "Begin descent" },
      { time: "09:00 AM", activity: "Reach base & start return journey" },
      { time: "09:30 AM", activity: "Visit Bhoga Nandishwara Temple & breakfast stop (self-funded)" },
      { time: "11:00 AM", activity: "Drop-off at your original pickup points in Bangalore" },
    ],
    included: [
      "Comfortable round-trip transportation from Bangalore",
      "Forest or trekking guide",
      "Trek lead from the Abhitrip Team",
      "Access to first-aid kit",
      "Forest permit if any (INCLUDED)",
    ],
    excluded: [
      "Meals (breakfast/snacks)",
      "Bottled water or other personal purchases",
      "Insurance or items not listed under inclusions",
    ],
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Nandi%20Hills%20One%20Day%20Trek.jpg-Tr34J8kEhyCUFRg6i5gKaJ1Vze0njR.jpeg",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    faqs: [
      {
        question: "What time do we start the trek?",
        answer: "We start early at 11:15 PM from Bangalore to catch the sunrise at Nandi Hills around 5:30 AM.",
      },
      {
        question: "Is this trek suitable for beginners?",
        answer:
          "Yes, this is an easy trek suitable for beginners and families. The trail is well-marked and not too steep.",
      },
      {
        question: "What should I wear?",
        answer:
          "Wear comfortable trekking shoes, warm clothes (it gets cold in the morning), and carry a light jacket.",
      },
    ],
    pickupPoints: [
      "Gopalan Arcade, RR Nagar - 11:15 PM",
      "Kathriguppe Circle - 11:30 PM",
      "BMTC Bus Stop, Banashankari - 11:45 PM",
      "Udupi Garden Signal, BTM Layout - 12:05 AM",
      "Bus Stop, Silk Board - 12:15 AM",
      "Shell Petrol Pump, Bellandur - 12:45 AM",
      "Opp. Kalamandir, Marathahalli - 01:15 AM",
      "HP Petrol Pump, Tin Factory - 01:35 AM",
      "Opp. Esteem Mall, Hebbal - 01:45 AM",
    ],
    cancellationPolicy:
      "Free cancellation up to 24 hours before the trip. 50% refund for cancellations within 24 hours.",
    thingsToCarry: [
      "A photocopy of your Aadhar/Voter ID (mandatory)",
      "Small backpack (to carry essentials)",
      "Water bottles – 1–2 liters",
      "Raincoat/poncho or bag cover (in case of rain)",
      "Trekking shoes with good grip + extra socks",
      "Torch/headlamp (required for night trek)",
      "Power bank",
      "Snacks (dry fruits, energy bars, etc.)",
      "Any personal medication",
    ],
  },
  {
    id: 2,
    title: "Uttari Betta Sunrise Trek",
    description:
      "Discover the historic charm of Uttari Betta (Hutridurga), just 70 km from Bangalore. This night trek takes you through lush grasslands, rocky trails and ancient fort gateways, culminating in a breathtaking sunrise view atop a serene hilltop temple.",
    detailedDescription:
      "Discover the historic charm of Uttari Betta (Hutridurga), just 70 km from Bangalore. This night trek takes you through lush grasslands, rocky trails and ancient fort gateways, culminating in a breathtaking sunrise view atop a serene hilltop temple. Perfect for adventure seekers looking for a quick escape into nature with historical significance.",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Uttaribetta%20One%20Day.jpg-Dclng3qBmPsE3nuxIRpuHpFloKThyG.jpeg",
    price: "₹799",
    originalPrice: "₹999",
    duration: "1 Day",
    difficulty: "Easy",
    groupSize: "15-25",
    rating: 4.6,
    reviews: 67,
    slug: "uttari-betta-sunrise-trek",
    highlights: [
      "Ideal for all trekkers - Beginners to seasoned hikers",
      "Ancient hill fort trail with scenic viewpoints",
      "Budget-friendly adventure",
      "Historic fort gateways and temple visit",
    ],
    location: "70km from Bangalore",
    category: "one-day",
    itinerary: [
      { time: "Day 0", activity: "Departure from Bengaluru at selected pickup points" },
      { time: "10:45 PM", activity: "Tin Factory (Benniganahalli Metro)" },
      { time: "11:05 PM", activity: "Opp. Kalamandir, Marathahalli" },
      { time: "11:20 PM", activity: "Akme Harmony, Bellandur" },
      { time: "11:35 PM", activity: "Silk Board Bus Stop" },
      { time: "11:50 PM", activity: "Udupi Garden Signal, BTM" },
      { time: "12:05 AM", activity: "Banashankari Bus Stop" },
      { time: "12:35 AM", activity: "Gopalan Arcade Mall, RR Nagar" },
      { time: "12:55 AM", activity: "Guraguntepalya Signal, Yeshwanthpur" },
      { time: "02:15 AM", activity: "Arrive at the base; quick rest" },
      { time: "02:45 AM", activity: "Start the trek with our experienced guides" },
      { time: "04:30 AM", activity: "Reach the summit and enjoy a peaceful sunrise" },
      { time: "05:45 AM", activity: "Begin descent" },
      { time: "06:15 AM", activity: "Halt for self-funded breakfast" },
      { time: "12:30 PM", activity: "Arrive back in Bangalore; same drop-off points" },
    ],
    included: [
      "Comfortable round-trip transportation from Bangalore",
      "Forest or trekking guide",
      "Trek lead from the Abhitrip Team",
      "Access to first-aid kit",
      "Forest permit if any (INCLUDED)",
    ],
    excluded: [
      "Meals (breakfast/snacks)",
      "Bottled water or other personal purchases",
      "Insurance or items not listed under inclusions",
    ],
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Uttaribetta%20One%20Day.jpg-Dclng3qBmPsE3nuxIRpuHpFloKThyG.jpeg",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    faqs: [
      {
        question: "How difficult is this trek?",
        answer: "It's an easy trek suitable for beginners with some rocky sections that add to the adventure.",
      },
      {
        question: "Can children participate?",
        answer: "Yes, children above 8 years can easily participate with adult supervision.",
      },
    ],
    pickupPoints: [
      "Tin Factory (Benniganahalli Metro) - 10:45 PM",
      "Opp. Kalamandir, Marathahalli - 11:05 PM",
      "Akme Harmony, Bellandur - 11:20 PM",
      "Silk Board Bus Stop - 11:35 PM",
      "Udupi Garden Signal, BTM - 11:50 PM",
      "Banashankari Bus Stop - 12:05 AM",
      "Gopalan Arcade Mall, RR Nagar - 12:35 AM",
      "Guraguntepalya Signal, Yeshwanthpur - 12:55 AM",
    ],
    cancellationPolicy: "Free cancellation up to 24 hours before the trip.",
    thingsToCarry: [
      "Small backpack to carry your essentials during the trek",
      "Water bottles 1-2 (1 liter each)",
      "Raincoat (poncho)/Bag covers in case of rains",
      "A comfortable pair of shoes with good grip for trekking with extra pair of socks",
      "Torch/Headlamp to be used at night",
      "Portable chargers for your electronics",
      "Eatables during trek Energy Booster, Tissues, Chocolates, Dry fruits, etc",
      "Personal Medication",
      "Snacks for yourself",
    ],
  },
  {
    id: 3,
    title: "Skandagiri Sunrise Trek",
    description:
      "Experience the magic of trekking under the stars and watching the sunrise from above the clouds! The Skandagiri Sunrise Trek offers an unforgettable night hike through ancient fort ruins, misty trails, and panoramic views of Nandi Hills and beyond.",
    detailedDescription:
      "Experience the magic of trekking under the stars and watching the sunrise from above the clouds! The Skandagiri Sunrise Trek offers an unforgettable night hike through ancient fort ruins, misty trails, and panoramic views of Nandi Hills and beyond. Just 70 km from Bangalore, this trek is perfect for both beginners and seasoned adventurers looking for a quick escape into nature.",
    image: "/placeholder.svg?height=300&width=400",
    price: "₹1249",
    originalPrice: "₹1499",
    duration: "1 Day",
    difficulty: "Moderate",
    groupSize: "15-20",
    rating: 4.8,
    reviews: 124,
    slug: "skandagiri-sunrise-trek",
    highlights: [
      "Early morning trek to one of Karnataka's most scenic sunrise points",
      "Mesmerizing sunrise view above the clouds",
      "360° views from the summit, often above the clouds",
      "Night trekking experience under the stars",
    ],
    location: "70km from Bangalore",
    category: "one-day",
    itinerary: [
      { time: "Day 0", activity: "Departure from Bengaluru" },
      { time: "10:45 PM", activity: "Gopalan Arcade, RR Nagar" },
      { time: "11:15 PM", activity: "BMTC Bus Stop, Banashankari" },
      { time: "11:35 PM", activity: "Udupi Garden Signal, BTM Layout" },
      { time: "11:45 PM", activity: "Bus Stop, Silk Board" },
      { time: "12:15 AM", activity: "Shell Petrol Pump, Bellandur" },
      { time: "12:45 AM", activity: "Opp. Kalamandir, Marathahalli" },
      { time: "01:05 AM", activity: "HP Petrol Pump, Tin Factory" },
      { time: "01:15 AM", activity: "Opp. Esteem Mall, Hebbal" },
      { time: "03:00 AM", activity: "Arrive at the base; rest or enjoy a calm walk under the stars" },
      { time: "05:30 AM", activity: "Begin trek after a safety briefing from our guides (Forest permit is included)" },
      { time: "07:15 AM", activity: "Reach the summit; enjoy sunrise and scenic cloud views" },
      { time: "08:00 AM", activity: "Start your descent" },
      { time: "10:00 AM", activity: "Reach base and board vehicle for return" },
      { time: "11:30 AM", activity: "Halt for self-funded breakfast & freshen-up" },
      { time: "01:00 PM", activity: "Arrive back in Bangalore; drop-off at your original pickup location" },
    ],
    included: [
      "Comfortable round-trip transportation from Bangalore",
      "Forest permit (INCLUDED)",
      "Trek lead from the Abhitrip Team",
      "Access to first-aid kit",
    ],
    excluded: [
      "Meals (breakfast/snacks)",
      "Bottled water or other personal purchases",
      "Insurance or items not listed under inclusions",
    ],
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    faqs: [
      {
        question: "Is this trek suitable for beginners?",
        answer:
          "Yes, though it's rated moderate, beginners with basic fitness can complete this trek with proper guidance.",
      },
      {
        question: "What makes this trek special?",
        answer:
          "The unique experience of trekking under stars and watching sunrise above clouds makes this trek extraordinary.",
      },
    ],
    pickupPoints: [
      "Gopalan Arcade, RR Nagar - 10:45 PM",
      "BMTC Bus Stop, Banashankari - 11:15 PM",
      "Udupi Garden Signal, BTM Layout - 11:35 PM",
      "Bus Stop, Silk Board - 11:45 PM",
      "Shell Petrol Pump, Bellandur - 12:15 AM",
      "Opp. Kalamandir, Marathahalli - 12:45 AM",
      "HP Petrol Pump, Tin Factory - 01:05 AM",
      "Opp. Esteem Mall, Hebbal - 01:15 AM",
    ],
    cancellationPolicy: "Free cancellation up to 24 hours before the trip.",
    thingsToCarry: [
      "A photocopy of your Aadhar/Voter ID (mandatory)",
      "Small backpack (to carry essentials)",
      "Water bottles – 1–2 liters",
      "Raincoat/poncho or bag cover (in case of rain)",
      "Trekking shoes with good grip + extra socks",
      "Torch/headlamp (required for night trek)",
      "Power bank",
      "Snacks (dry fruits, energy bars, etc.)",
      "Any personal medication",
    ],
  },
  {
    id: 4,
    title: "Shivagange Sunrise Trek",
    description:
      "Ascend the sacred peak of Shivagange, known as 'Dakshina Kashi,' located just ~60 km from Bangalore. This moderate night trek weaves through temples, rocky terrain, and lush landscapes, culminating in a beautiful sunrise at the summit—perfect for a quick spiritual and scenic escape.",
    detailedDescription:
      "Ascend the sacred peak of Shivagange, known as 'Dakshina Kashi,' located just ~60 km from Bangalore. This moderate night trek weaves through temples, rocky terrain, and lush landscapes, culminating in a beautiful sunrise at the summit—perfect for a quick spiritual and scenic escape. The trek combines adventure with spirituality, offering both physical challenge and mental peace.",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Shivgange%20One%20Day%20trek.jpg-nJpofElfLfobwj1ga1SR31smvYNZIv.jpeg",
    price: "₹799",
    originalPrice: "₹999",
    duration: "1 Day",
    difficulty: "Moderate",
    groupSize: "15-25",
    rating: 4.5,
    reviews: 78,
    slug: "shivagange-sunrise-trek",
    highlights: [
      "Short, convenient getaway from Bangalore",
      "Spectacular sunrise from a culturally significant hillpeak",
      "Moderate night trek featuring sacred shrines and rocky trails",
      "Visit to ancient temples and spiritual sites",
    ],
    location: "60km from Bangalore",
    category: "one-day",
    itinerary: [
      { time: "Day 0", activity: "Departure from Bengaluru" },
      { time: "10:45 PM", activity: "Tin Factory (Benniganahalli Metro)" },
      { time: "11:05 PM", activity: "Opp. Kalamandir, Marathahalli" },
      { time: "11:20 PM", activity: "Akme Harmony, Bellandur" },
      { time: "11:35 PM", activity: "Silk Board Bus Stop" },
      { time: "11:50 PM", activity: "Udupi Garden Signal, BTM" },
      { time: "12:05 AM", activity: "Banashankari Bus Stop" },
      { time: "12:35 AM", activity: "Gopalan Arcade Mall, RR Nagar" },
      { time: "12:55 AM", activity: "Guraguntepalya Signal, Yeshwanthpur" },
      { time: "02:30 AM", activity: "Arrive at the base; Quick rest" },
      { time: "03:00 AM", activity: "Begin ascent through rocky steps and temple trail" },
      { time: "05:30 AM", activity: "Reach summit; enjoy sunrise and panoramic views" },
      { time: "07:00 AM", activity: "Descend back to the base" },
      { time: "07:30 AM", activity: "Halt for a self-funded breakfast" },
      { time: "12:30 PM", activity: "Return to Bangalore; same drop-off points" },
    ],
    included: [
      "Comfortable round-trip transportation from Bangalore",
      "Forest or trekking guide",
      "Trek lead from the Abhitrip Team",
      "Access to first-aid kit",
      "Forest permit if any (INCLUDED)",
    ],
    excluded: [
      "Meals (breakfast/snacks)",
      "Bottled water or other personal purchases",
      "Insurance or items not listed under inclusions",
    ],
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Shivgange%20One%20Day%20trek.jpg-nJpofElfLfobwj1ga1SR31smvYNZIv.jpeg",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    faqs: [
      {
        question: "What is the spiritual significance of Shivagange?",
        answer:
          "Shivagange is known as 'Dakshina Kashi' and is considered one of the most sacred hills in Karnataka with ancient temples.",
      },
      {
        question: "Is this trek suitable for families?",
        answer:
          "Yes, families with children above 10 years can participate, though it requires moderate fitness levels.",
      },
    ],
    pickupPoints: [
      "Tin Factory (Benniganahalli Metro) - 10:45 PM",
      "Opp. Kalamandir, Marathahalli - 11:05 PM",
      "Akme Harmony, Bellandur - 11:20 PM",
      "Silk Board Bus Stop - 11:35 PM",
      "Udupi Garden Signal, BTM - 11:50 PM",
      "Banashankari Bus Stop - 12:05 AM",
      "Gopalan Arcade Mall, RR Nagar - 12:35 AM",
      "Guraguntepalya Signal, Yeshwanthpur - 12:55 AM",
    ],
    cancellationPolicy: "Free cancellation up to 24 hours before the trip.",
    thingsToCarry: [
      "A photocopy of your Aadhar/Voter ID (mandatory)",
      "Small backpack (to carry essentials)",
      "Water bottles – 1–2 liters",
      "Raincoat/poncho or bag cover (in case of rain)",
      "Trekking shoes with good grip + extra socks",
      "Torch/headlamp (required for night trek)",
      "Power bank",
      "Snacks (dry fruits, energy bars, etc.)",
      "Any personal medication",
    ],
  },
  {
    id: 5,
    title: "Kunti Betta Sunrise Trek",
    description:
      "Looking for a thrilling night trek with breathtaking sunrise views? The Kunti Betta Sunrise Trek is the perfect blend of adventure, nature, and mythology, just 125 km from Bangalore in the historic town of Pandavapura, near Mysore.",
    detailedDescription:
      "Looking for a thrilling night trek with breathtaking sunrise views? The Kunti Betta Sunrise Trek is the perfect blend of adventure, nature, and mythology, just 125 km from Bangalore in the historic town of Pandavapura, near Mysore. This trek offers a unique combination of mythological significance and natural beauty, making it perfect for adventure enthusiasts.",
    image: "/placeholder.svg?height=300&width=400",
    price: "₹799",
    originalPrice: "₹999",
    duration: "1 Day",
    difficulty: "Easy",
    groupSize: "15-20",
    rating: 4.4,
    reviews: 56,
    slug: "kunti-betta-sunrise-trek",
    highlights: [
      "Night trek with flashlight-lit trails under the star",
      "Sunrise view from the summit with 360° panoramic beauty",
      "Budget-friendly adventure",
      "Mythological significance connected to Mahabharata",
    ],
    location: "125km from Bangalore",
    category: "one-day",
    itinerary: [
      { time: "Day 0", activity: "Departure from Bengaluru" },
      { time: "11:15 PM", activity: "Benniganahalli Metro Station, Tin Factory" },
      { time: "11:35 PM", activity: "Kalamandir, Marathahalli" },
      { time: "11:50 PM", activity: "Akme Harmony, Bellandur" },
      { time: "12:05 AM", activity: "Silkboard Bus Stop" },
      { time: "12:15 AM", activity: "Udupi Garden Signal, BTM" },
      { time: "12:30 AM", activity: "Banashankari Bus Stop" },
      { time: "12:45 AM", activity: "Kathriguppe Circle" },
      { time: "01:00 AM", activity: "Gopalan Arcade Mall, RR Nagar" },
      { time: "01:15 AM", activity: "Kengeri Bus Stop" },
      { time: "03:30 AM", activity: "Arrive at Kunti Betta base" },
      { time: "03:45 AM", activity: "Briefing by the trek guide" },
      { time: "04:00 AM", activity: "Begin the night trek" },
      { time: "05:00 AM", activity: "Reach the summit & enjoy the sunrise" },
      { time: "06:30 AM", activity: "Start descent" },
      { time: "09:30 AM", activity: "Breakfast stop (self-funded)" },
      { time: "11:00 AM", activity: "Depart for Bangalore" },
      { time: "01:00 PM", activity: "Drop-off at original pickup points" },
    ],
    included: [
      "Comfortable round-trip transportation from Bangalore",
      "Forest or trekking guide",
      "Trek lead from the Abhitrip Team",
      "Access to first-aid kit",
      "Forest permit if any (INCLUDED)",
    ],
    excluded: [
      "Meals (breakfast/snacks)",
      "Bottled water or other personal purchases",
      "Insurance or items not listed under inclusions",
    ],
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    faqs: [
      {
        question: "What is the mythological significance of Kunti Betta?",
        answer:
          "Kunti Betta is believed to be connected to the Mahabharata, where Kunti (mother of Pandavas) is said to have stayed here.",
      },
      {
        question: "Is this trek suitable for beginners?",
        answer: "Yes, this is an easy trek perfect for beginners and families looking for a night trekking experience.",
      },
    ],
    pickupPoints: [
      "Benniganahalli Metro Station, Tin Factory - 11:15 PM",
      "Kalamandir, Marathahalli - 11:35 PM",
      "Akme Harmony, Bellandur - 11:50 PM",
      "Silkboard Bus Stop - 12:05 AM",
      "Udupi Garden Signal, BTM - 12:15 AM",
      "Banashankari Bus Stop - 12:30 AM",
      "Kathriguppe Circle - 12:45 AM",
      "Gopalan Arcade Mall, RR Nagar - 01:00 AM",
      "Kengeri Bus Stop - 01:15 AM",
    ],
    cancellationPolicy: "Free cancellation up to 24 hours before the trip.",
    thingsToCarry: [
      "A photocopy of your Aadhar/Voter ID (mandatory)",
      "Small backpack (to carry essentials)",
      "Water bottles – 1–2 liters",
      "Raincoat/poncho or bag cover (in case of rain)",
      "Trekking shoes with good grip + extra socks",
      "Torch/headlamp (required for night trek)",
      "Power bank",
      "Snacks (dry fruits, energy bars, etc.)",
      "Any personal medication",
    ],
  },
  {
    id: 6,
    title: "Adiyogi & Gudibande Fort Trek",
    description:
      "Embark on a unique day adventure where spiritual calm and historic thrill come together! The Adiyogi & Gudibande Fort Trek offers the perfect blend of peaceful vibes, scenic views, and a short hike — making it an ideal getaway for both beginners and weekend explorers.",
    detailedDescription:
      "Embark on a unique day adventure where spiritual calm and historic thrill come together! The Adiyogi & Gudibande Fort Trek offers the perfect blend of peaceful vibes, scenic views, and a short hike — making it an ideal getaway for both beginners and weekend explorers. Experience the majestic Adiyogi statue and explore the ancient Gudibande Fort in one memorable day trip.",
    image: "/placeholder.svg?height=300&width=400",
    price: "₹999",
    originalPrice: "₹1299",
    duration: "1 Day",
    difficulty: "Easy",
    groupSize: "15-25",
    rating: 4.6,
    reviews: 92,
    slug: "adiyogi-gudibande-fort-trek",
    highlights: [
      "Visit the Adiyogi Shiva statue for a peaceful start",
      "Easy-to-moderate trek to Gudibande Fort (around 400 steps)",
      "Explore the centuries-old fort and rainwater harvesting systems",
      "Special laser show at Adiyogi",
    ],
    location: "80km from Bangalore",
    category: "one-day",
    itinerary: [
      { time: "08:00 AM", activity: "BTM (Near A2B)" },
      { time: "08:10 AM", activity: "Silkboard (Udupi Upachar)" },
      { time: "08:20 AM", activity: "Bellandur Bus Stop" },
      { time: "08:30 AM", activity: "Marathahalli (Opp. Kalamandir)" },
      { time: "08:45 AM", activity: "Tin Factory" },
      { time: "08:00 AM", activity: "Start from Bangalore (breakfast on the way)" },
      { time: "10:30 AM", activity: "Arrive at Gudibande Fort & begin trek" },
      { time: "11:30 AM", activity: "Relax & enjoy summit views" },
      { time: "01:00 PM", activity: "Lunch stop" },
      { time: "05:30 PM", activity: "Reach Adiyogi, explore and attend Divya Darshan" },
      { time: "07:30 PM", activity: "Enjoy the special laser show" },
      { time: "10:00 PM", activity: "Dinner stop (self-sponsored)" },
      { time: "11:30 PM - 12:00 AM", activity: "Drop back to Bangalore" },
    ],
    included: [
      "Comfortable round-trip transportation from Bangalore",
      "Breakfast (In pure veg restaurant)",
      "Tea/Coffee",
      "All toll & permits",
      "Entry tickets",
      "Abhitrip Coordinator",
    ],
    excluded: [
      "Meals (lunch)",
      "Bottled water or other personal purchases",
      "Insurance or items not listed under inclusions",
    ],
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    faqs: [
      {
        question: "What is special about the Adiyogi statue?",
        answer:
          "The Adiyogi statue is a 112-foot tall statue of Lord Shiva, recognized by Guinness World Records as the largest bust sculpture.",
      },
      {
        question: "Is the trek to Gudibande Fort difficult?",
        answer: "No, it's an easy trek with around 400 steps. Suitable for all age groups and fitness levels.",
      },
    ],
    pickupPoints: [
      "BTM (Near A2B) - 08:00 AM",
      "Silkboard (Udupi Upachar) - 08:10 AM",
      "Bellandur Bus Stop - 08:20 AM",
      "Marathahalli (Opp. Kalamandir) - 08:30 AM",
      "Tin Factory - 08:45 AM",
    ],
    cancellationPolicy: "Free cancellation up to 24 hours before the trip.",
    thingsToCarry: [
      "Backpack to carry your essentials",
      "Water bottles (1 litre, plastic bottle not allowed)",
      "Sunscreen and Suncap",
      "Energy bars and snacks",
    ],
  },
  // Two Day Trips
  {
    id: 101,
    title: "Coorg Trip – The Scotland of India",
    description:
      "Discover the lush beauty and cultural richness of Coorg – often hailed as the 'Scotland of India.' From majestic viewpoints and roaring waterfalls to spiritual sanctuaries and elephant encounters, this 2-day escape is crafted for nature lovers, photographers, and adventure seekers. Ideal for solo travelers, friends, and weekend wanderers.",
    detailedDescription:
      "Discover the lush beauty and cultural richness of Coorg – often hailed as the 'Scotland of India.' From majestic viewpoints and roaring waterfalls to spiritual sanctuaries and elephant encounters, this 2-day escape is crafted for nature lovers, photographers, and adventure seekers. Ideal for solo travelers, friends, and weekend wanderers.",
    image:
      "https://images.unsplash.com/photo-1669744665015-33f3a2f657b3?q=80&w=1342&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: "₹3,999",
    originalPrice: "₹4,499",
    duration: "2 Days / 1 Night",
    difficulty: "Easy",
    groupSize: "15-20",
    rating: 4.8,
    reviews: 124,
    slug: "coorg-trip",
    highlights: ["Mandalpatti View Point", "Abbey Falls", "Raja Seat", "Harangi Elephant Camp", "Namdroling Monastery"],
    location: "250km from Bangalore",
    category: "two-day",
    itinerary: [
      { time: "Day 0 – 10:00 PM", activity: "Begin Your Scenic Journey to the Hills of Kodagu" },
      { time: "10:00 PM", activity: "Start from Banashankari" },
      { time: "10:15 PM", activity: "Quick pickup at BTM Layout" },
      { time: "10:30 PM", activity: "Stop at Silk Board" },
      { time: "10:45 PM", activity: "Board at Bellandur" },
      { time: "11:00 PM", activity: "Assemble at Marathahalli" },
      { time: "11:30 PM", activity: "Pickup at Tin Factory" },
      { time: "12:30 PM", activity: "Board at Mysuru Road Bus Station" },
      { time: "12:50 PM", activity: "Final pickup at RR Nagar Arcade" },
      { time: "Day 1: Royal Exploration in Coorg", activity: "" },
      { time: "06:00 – 09:30 AM", activity: "Arrival, check-in, freshen up, and breakfast" },
      { time: "09:30 – 01:00 PM", activity: "Visit Mandalpatti View Point (optional jeep ride)" },
      { time: "01:00 – 02:00 PM", activity: "Lunch break (self-sponsored)" },
      { time: "02:00 – 03:00 PM", activity: "Explore Kote Abbey Falls" },
      { time: "03:45 – 06:30 PM", activity: "Visit Raja Seat and soak in the sunset" },
      { time: "06:30 – 07:00 PM", activity: "Visit the Omkareshwar Temple" },
      { time: "07:30 PM", activity: "Return to stay, Campfire & Dinner" },
      { time: "Day 2: A Tryst with Nature & Spirituality", activity: "" },
      { time: "10:00 – 11:00 AM", activity: "Breakfast and head to Harangi Elephant Camp" },
      { time: "11:00 – 12:30 PM", activity: "Elephant interaction (optional activities)" },
      { time: "12:30 – 02:00 PM", activity: "Lunch break (self-sponsored)" },
      { time: "02:00 – 05:00 PM", activity: "Explore Namdroling Monastery" },
      { time: "05:00 PM", activity: "Start return journey to Bangalore" },
      { time: "10:00 PM", activity: "Reach Bangalore (same drop points as pickup)" },
    ],
    included: [
      "Non-A/C Transport from Bangalore (Round Trip)",
      "2 Breakfasts and 1 Dinner (Veg)",
      "Forest/Trek Permits",
      "Dormitory Accommodation (Separate for Men and Women)",
      "Abhi Trip Trek Coordinator",
      "Basic First Aid Kit",
    ],
    excluded: [
      "Optional Activities (Jeep ride, elephant interaction)",
      "Personal Expenses: Snacks, Bottled Water, Additional Meals",
      "Insurance of any kind",
      "Anything not listed in the 'Inclusions'",
    ],
    gallery: [
      "https://images.unsplash.com/photo-1669744665015-33f3a2f657b3?q=80&w=1342&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    faqs: [
      {
        question: "What type of accommodation is provided?",
        answer:
          "We provide comfortable dormitory accommodation with separate arrangements for men and women, including all basic amenities.",
      },
      {
        question: "Is the Mandalpatti jeep safari included?",
        answer: "The jeep safari to Mandalpatti viewpoint is optional and requires additional payment.",
      },
      {
        question: "What's the best time to visit Coorg?",
        answer:
          "October to March is ideal for pleasant weather. Monsoon season (June-September) offers lush greenery but may have travel restrictions.",
      },
    ],
    pickupPoints: [
      "Banashankari - 10:00 PM",
      "BTM Layout - 10:15 PM",
      "Silk Board - 10:30 PM",
      "Bellandur - 10:45 PM",
      "Marathahalli - 11:00 PM",
      "Tin Factory - 11:30 PM",
      "Mysuru Road Bus Station - 12:30 PM",
      "RR Nagar Arcade - 12:50 PM",
    ],
    cancellationPolicy:
      "Free cancellation up to 48 hours before departure. 50% refund for cancellations within 48 hours.",
    thingsToCarry: [
      "Xerox Copy of your Aadhar/Voter ID",
      "Small backpack",
      "Water bottles (1–2 liters)",
      "Comfortable trekking shoes with good grip",
      "Raincoat and bag covers",
      "Extra pair of clothes",
      "Torch or Headlamp",
      "Personal medication",
      "Hand sanitizers",
      "Portable chargers",
      "Chocolates, energy bars, dry fruits",
      "Snacks",
    ],
  },
  {
    id: 102,
    title: "Chikmagalur Backpacking Trip",
    description:
      "Escape into the heart of Karnataka's Western Ghats with our Chikmagalur Backpacking Trip. Misty peaks, hidden waterfalls, ancient temples, and lakeside sunsets all packed into a perfect weekend getaway.",
    detailedDescription:
      "Escape into the heart of Karnataka's Western Ghats with our Chikmagalur Backpacking Trip. Misty peaks, hidden waterfalls, ancient temples, and lakeside sunsets all packed into a perfect weekend getaway. Experience the coffee capital of India with its scenic landscapes and rich cultural heritage.",
    image:
      "https://images.unsplash.com/photo-1526392060635-9d6019884377?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
    price: "₹3,999",
    originalPrice: "₹4,499",
    duration: "2 Days / 1 Night",
    difficulty: "Easy",
    groupSize: "15-20",
    rating: 4.7,
    reviews: 98,
    slug: "chikmagalur-trip",
    highlights: [
      "Mullayanagiri Peak",
      "Bababudangiri",
      "Z Point",
      "Beluru Temple",
      "Honnamana Halla Falls",
      "Hirekolale Lake",
    ],
    location: "240km from Bangalore",
    category: "two-day",
    itinerary: [
      { time: "Day 0 – 10:00 PM", activity: "Begin Your Scenic Journey to the Chikmagalur" },
      { time: "10:00 PM", activity: "Start from Banashankari bus stop" },
      { time: "10:15 PM", activity: "Join from BTM Layout" },
      { time: "10:30 PM", activity: "Next stop, Silk Board" },
      { time: "10:45 PM", activity: "Assemble at Koramangala" },
      { time: "11:00 PM", activity: "Picking up at Domlur" },
      { time: "11:15 PM", activity: "Meet us at MG Road" },
      { time: "11:30 PM", activity: "Join at KTM Mekhri Circle" },
      { time: "11:45 PM", activity: "Board at Yeshwanthpura" },
      { time: "12:00 AM", activity: "Last pickup at Goraguntepalya" },
      { time: "Day 1 – Peaks, Falls & Sunset Lakes", activity: "" },
      { time: "06:00 – 09:00 AM", activity: "Arrive at Chikmagalur and head to Mullayanagiri Peak" },
      { time: "09:00 – 10:00 AM", activity: "Check-in, freshen up, and breakfast" },
      { time: "10:00 – 02:00 PM", activity: "Visit Honnammana Halla Falls, Baba Budangiri, and Z Point" },
      { time: "02:00 – 03:30 PM", activity: "Lunch break" },
      { time: "04:00 – 06:00 PM", activity: "Visit Hirekolale Lake for sunset" },
      { time: "06:30 PM", activity: "Return to stay, campfire, and veg dinner" },
      { time: "Day 2 – Adventure & Temples", activity: "" },
      { time: "09:00 AM", activity: "Breakfast and checkout" },
      { time: "10:00 – 01:00 PM", activity: "Water sports at Yagachi Dam (self-sponsored)" },
      { time: "01:00 – 02:00 PM", activity: "Lunch en route to Belur" },
      { time: "02:00 – 03:00 PM", activity: "Visit Chennakeshava Temple, Belur" },
      { time: "03:00 – 04:00 PM", activity: "Explore Hoysaleshwara Temple, Halebeedu" },
      { time: "04:00 PM", activity: "Depart for Bangalore" },
      { time: "08:00 PM", activity: "Dinner stop" },
      { time: "10:00 PM", activity: "Arrive in Bangalore (same drop points)" },
    ],
    included: [
      "Non-A/C Transport from Bangalore (Round Trip)",
      "2 Breakfasts and 1 Dinner (Veg)",
      "Forest/Trek Permits",
      "Dormitory Accommodation (Separate for Men and Women)",
      "Abhi Trip Trek Coordinator",
      "Basic First Aid Kit",
    ],
    excluded: [
      "Optional Activities (Jeep ride, elephant interaction)",
      "Personal Expenses: Snacks, Bottled Water, Additional Meals",
      "Insurance of any kind",
      "Anything not listed in the 'Inclusions'",
    ],
    gallery: [
      "https://images.unsplash.com/photo-1526392060635-9d6019884377?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    faqs: [
      {
        question: "What is the difficulty level of this trip?",
        answer: "This is an easy trip suitable for all age groups and fitness levels.",
      },
      {
        question: "Are water sports included in the package?",
        answer: "Water sports at Yagachi Dam are optional and require additional payment.",
      },
    ],
    pickupPoints: [
      "Banashankari bus stop - 10:00 PM",
      "BTM Layout - 10:15 PM",
      "Silk Board - 10:30 PM",
      "Koramangala - 10:45 PM",
      "Domlur - 11:00 PM",
      "MG Road - 11:15 PM",
      "KTM Mekhri Circle - 11:30 PM",
      "Yeshwanthpura - 11:45 PM",
      "Goraguntepalya - 12:00 AM",
    ],
    cancellationPolicy: "Free cancellation up to 48 hours before departure.",
    thingsToCarry: [
      "Xerox Copy of your Aadhar/Voter ID",
      "Small backpack",
      "Water bottles (1–2 liters)",
      "Comfortable trekking shoes with good grip",
      "Raincoat and bag covers",
      "Extra pair of clothes",
      "Torch or Headlamp",
      "Personal medication",
      "Hand sanitizers",
      "Portable chargers",
      "Chocolates, energy bars, dry fruits",
      "Snacks",
    ],
  },
  {
    id: 103,
    title: "Gokarna and Murudeshwar Trip",
    description:
      "A perfect weekend escape combining beach bliss and spiritual vibes. Relax on serene shores, explore scenic trails, and visit iconic coastal temples.",
    detailedDescription:
      "A perfect weekend escape combining beach bliss and spiritual vibes. Relax on serene shores, explore scenic trails, and visit iconic coastal temples. Experience the best of Karnataka's coastline with pristine beaches and ancient temples.",
    image:
      "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1074&q=80",
    price: "₹3,699",
    originalPrice: "₹4,199",
    duration: "2 Days / 1 Night",
    difficulty: "Easy",
    groupSize: "15-18",
    rating: 4.6,
    reviews: 87,
    slug: "gokarna-murudeshwar-trip",
    highlights: [
      "Mahabaleshwar Temple",
      "Mirjan Fort",
      "Om Beach",
      "Kudle Beach",
      "Murudeshwar - Shiva Statue",
      "Honnavara Backwaters",
    ],
    location: "480km from Bangalore",
    category: "two-day",
    itinerary: [
      { time: "Day 0 – 08:00 PM", activity: "Begin Your Scenic Journey to the Gokarna" },
      { time: "08:00 PM", activity: "Start from Banashankari bus stop" },
      { time: "08:15 PM", activity: "Join from BTM Layout" },
      { time: "08:30 PM", activity: "Next stop, Silk Board" },
      { time: "08:45 PM", activity: "Assemble at Koramangala" },
      { time: "09:00 PM", activity: "Picking up at Domlur" },
      { time: "09:15 PM", activity: "Meet us at MG Road" },
      { time: "09:30 PM", activity: "Join at KTM Mekhri Circle" },
      { time: "09:45 PM", activity: "Board at Yeshwanthpura" },
      { time: "10:00 PM", activity: "Last pickup at Goraguntepalya" },
      { time: "Day 1 – Forts and Beaches", activity: "" },
      { time: "09:00 – 11:00 AM", activity: "Arrival at campsite, freshen up and relax" },
      { time: "11:00 – 12:00 PM", activity: "Visit Mahabaleshwar Temple (Temple closes at 12:30 PM)" },
      { time: "12:30 – 01:30 PM", activity: "Explore the historic Mirjan Fort" },
      { time: "01:30 – 02:30 PM", activity: "Lunch break (Self-sponsored)" },
      { time: "04:00 – 05:00 PM", activity: "Visit Om Beach, followed by a short trek (1 km) to Kudle Beach" },
      { time: "05:30 – 06:30 PM", activity: "Sunset at Kudle Beach" },
      { time: "06:30 – 10:00 PM", activity: "Return to campsite, enjoy campfire, group bonding, and dinner" },
      { time: "Day 2 – Temples, Boating & Return", activity: "" },
      { time: "06:00 – 09:00 AM", activity: "Wake up, freshen up, and enjoy breakfast" },
      { time: "09:00 – 12:00 PM", activity: "Visit Murudeshwar Temple and return" },
      { time: "12:00 – 02:30 PM", activity: "Honnavara Boating" },
      { time: "02:30 – 03:30 PM", activity: "Lunch" },
      { time: "Post 03:30 PM", activity: "Depart for Bengaluru" },
      { time: "Dinner en route (Self-sponsored)", activity: "" },
      { time: "05:00 AM", activity: "Reach Bangalore" },
    ],
    included: [
      "Non-A/C Transport from Bangalore (Round Trip)",
      "2 Breakfasts and 1 Dinner (Veg)",
      "Forest/Trek Permits",
      "Dormitory Accommodation (Separate for Men and Women)",
      "Abhi Trip Trek Coordinator",
      "Basic First Aid Kit",
    ],
    excluded: [
      "Optional Activities",
      "Personal Expenses: Snacks, Bottled Water, Additional Meals",
      "Insurance of any kind",
      "Anything not listed in the 'Inclusions'",
    ],
    gallery: [
      "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1074&q=80",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    faqs: [
      {
        question: "Is swimming allowed at the beaches?",
        answer:
          "Yes, swimming is allowed at designated areas. Please follow safety guidelines and swim at your own risk.",
      },
      {
        question: "What is the temple timing?",
        answer: "Mahabaleshwar Temple closes at 12:30 PM, so we visit early morning to ensure darshan.",
      },
    ],
    pickupPoints: [
      "Banashankari bus stop - 08:00 PM",
      "BTM Layout - 08:15 PM",
      "Silk Board - 08:30 PM",
      "Koramangala - 08:45 PM",
      "Domlur - 09:00 PM",
      "MG Road - 09:15 PM",
      "KTM Mekhri Circle - 09:30 PM",
      "Yeshwanthpura - 09:45 PM",
      "Goraguntepalya - 10:00 PM",
    ],
    cancellationPolicy: "Free cancellation up to 48 hours before departure.",
    thingsToCarry: [
      "Xerox Copy of your Aadhar/Voter ID",
      "Small backpack",
      "Water bottles (1–2 liters)",
      "Comfortable trekking shoes with good grip",
      "Raincoat and bag covers",
      "Extra pair of clothes",
      "Torch or Headlamp",
      "Personal medication",
      "Hand sanitizers",
      "Portable chargers",
      "Chocolates, energy bars, dry fruits",
      "Snacks",
    ],
  },
  {
    id: 104,
    title: "Netravati Trek",
    description:
      "The Netravathi Trek is a thrilling 2-day escape into the heart of the Western Ghats. Day 1 offers serene visits to Samse Tea Estate, Horanadu Temple, and Soormane Falls. Day 2 takes you on a rewarding trek to the remote and scenic Netravathi Peak.",
    detailedDescription:
      "The Netravathi Trek is a thrilling 2-day escape into the heart of the Western Ghats. Day 1 offers serene visits to Samse Tea Estate, Horanadu Temple, and Soormane Falls. Day 2 takes you on a rewarding trek to the remote and scenic Netravathi Peak. Experience the pristine beauty of Karnataka's mountain ranges.",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Netravati%20Trek%20Two%20Day.jpg-xxpUEATovirX0mWbFkiEKBPqNaIbW8.jpeg",
    price: "₹3,899",
    originalPrice: "₹4,399",
    duration: "2 Days / 1 Night",
    difficulty: "Moderate",
    groupSize: "12-15",
    rating: 4.9,
    reviews: 56,
    slug: "netravati-trek",
    highlights: [
      "Netravathi Peak Trek",
      "Samse Tea Estate",
      "Horanadu Temple",
      "Soormane Falls",
      "Kalasa Hanging Bridge",
    ],
    location: "300km from Bangalore",
    category: "two-day",
    itinerary: [
      { time: "Day 0 – 08:00 PM", activity: "Begin Your Scenic Journey to the Netravathi" },
      { time: "08:00 PM", activity: "Start from Banashankari bus stop" },
      { time: "08:15 PM", activity: "Join from BTM Layout" },
      { time: "08:30 PM", activity: "Next stop, Silk Board" },
      { time: "08:45 PM", activity: "Assemble at Koramangala" },
      { time: "09:00 PM", activity: "Picking up at Domlur" },
      { time: "09:15 PM", activity: "Meet us at MG Road" },
      { time: "09:30 PM", activity: "Join at KTM Mekhri Circle" },
      { time: "09:45 PM", activity: "Board at Yeshwanthpura" },
      { time: "10:00 PM", activity: "Last pickup at Goraguntepalya" },
      { time: "Day 1 – The Netravati Peak Trek", activity: "" },
      { time: "06:00 AM", activity: "Arrive at homestay and freshen up" },
      { time: "07:00 AM", activity: "Breakfast & packed lunch distribution" },
      { time: "07:30 AM", activity: "Jeep ride to Netravati Trek base & trek to the summit (~6.5 hrs)" },
      { time: "02:00 PM", activity: "Enjoy lunch with panoramic views at the peak" },
      { time: "03:00 PM", activity: "Descend to the base (3 hrs)" },
      { time: "06:00 PM", activity: "Refresh with hot tea at the homestay" },
      { time: "06:30 PM", activity: "Campfire night, stories, games, dinner & rest" },
      { time: "Day 2 – Culture & Nature Tour", activity: "" },
      { time: "07:00 AM", activity: "Breakfast + Visit to Samse Tea Estates" },
      { time: "11:00 AM", activity: "Head to Adi-Shaktyamaka Shri Annapoorneshwari Temple (Horanadu)" },
      { time: "12:00 PM", activity: "Stop at the serene Kodige Waterfalls" },
      { time: "01:30 PM", activity: "Lunch" },
      { time: "02:30 PM", activity: "Visit the magnificent Belur Temple" },
      { time: "08:00 PM", activity: "Dinner en route (Self-sponsored)" },
      { time: "10:00 PM", activity: "Arrive back in Bengaluru" },
    ],
    included: [
      "Non-A/C round-trip transport from Bangalore",
      "2 Breakfasts, 1 Packed lunch, and 1 Veg dinner",
      "All required permits and entry fees",
      "Dormitory accommodation (separate for men and women)",
      "Abhi Trip trek coordinator",
      "Basic first aid kit",
    ],
    excluded: [
      "Optional Activities",
      "Personal Expenses: Snacks, Bottled Water, Additional Meals",
      "Insurance of any kind",
      "Anything not listed in the 'Inclusions'",
    ],
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Netravati%20Trek%20Two%20Day.jpg-xxpUEATovirX0mWbFkiEKBPqNaIbW8.jpeg",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    faqs: [
      {
        question: "What is the difficulty level of Netravati trek?",
        answer: "This is a moderate level trek requiring basic fitness. The trek duration is approximately 6.5 hours.",
      },
      {
        question: "Is the jeep ride to base included?",
        answer: "Yes, the jeep ride to the trek starting point is included in the package.",
      },
    ],
    pickupPoints: [
      "Banashankari bus stop - 08:00 PM",
      "BTM Layout - 08:15 PM",
      "Silk Board - 08:30 PM",
      "Koramangala - 08:45 PM",
      "Domlur - 09:00 PM",
      "MG Road - 09:15 PM",
      "KTM Mekhri Circle - 09:30 PM",
      "Yeshwanthpura - 09:45 PM",
      "Goraguntepalya - 10:00 PM",
    ],
    cancellationPolicy: "Free cancellation up to 48 hours before departure.",
    thingsToCarry: [
      "Xerox Copy of your Aadhar/Voter ID",
      "Small backpack",
      "Water bottles (1–2 liters)",
      "Comfortable trekking shoes with good grip",
      "Raincoat and bag covers",
      "Extra pair of clothes",
      "Torch or Headlamp",
      "Personal medication",
      "Hand sanitizers",
      "Portable chargers",
      "Chocolates, energy bars, dry fruits",
      "Snacks",
    ],
  },
  {
    id: 105,
    title: "Bandaje Falls Trek",
    description:
      "Bandaje Falls Trek is a scenic adventure through the Western Ghats, leading to a stunning waterfall hidden amidst lush forests and rolling hills. Perfect for nature lovers and thrill-seekers alike.",
    detailedDescription:
      "Bandaje Falls Trek is a scenic adventure through the Western Ghats, leading to a stunning waterfall hidden amidst lush forests and rolling hills. Perfect for nature lovers and thrill-seekers alike. Experience the pristine beauty of one of Karnataka's most spectacular waterfalls.",
    image: "/placeholder.svg?height=300&width=400",
    price: "₹3,899",
    originalPrice: "₹4,399",
    duration: "2 Days / 1 Night",
    difficulty: "Moderate",
    groupSize: "12-15",
    rating: 4.8,
    reviews: 72,
    slug: "bandaje-falls-trek",
    highlights: [
      "Bandaje Falls Trek",
      "Ballarayana Durga Fort",
      "Samse Tea Estate",
      "Horanadu Temple",
      "Soormane Falls",
      "Kalasa Hanging Bridge",
    ],
    location: "320km from Bangalore",
    category: "two-day",
    itinerary: [
      { time: "Day 0 – 08:00 PM", activity: "Begin Your Scenic Journey to the Bandaje Trek" },
      { time: "08:00 PM", activity: "Start from Banashankari bus stop" },
      { time: "08:15 PM", activity: "Join from Ragigudda Metro Station" },
      { time: "08:30 PM", activity: "Next stop, Silk Board" },
      { time: "08:45 PM", activity: "Assemble at Koramangala" },
      { time: "09:00 PM", activity: "Picking up at Domlur" },
      { time: "09:15 PM", activity: "Meet us at MG Road" },
      { time: "09:30 PM", activity: "Join at KTM Mekhri Circle" },
      { time: "09:45 PM", activity: "Board at Yeshwanthpura" },
      { time: "10:00 PM", activity: "Last pickup at Goraguntepalya" },
      { time: "Day 1 – Waterfalls for the Eyes, Temple for the Soul", activity: "" },
      { time: "06:00 – 07:00 AM", activity: "Check-in at the homestay" },
      { time: "07:00 – 08:00 AM", activity: "Freshen up and enjoy breakfast" },
      { time: "09:00 – 10:00 AM", activity: "Visit the scenic Samse Tea Estate" },
      {
        time: "10:30 – 12:30 PM",
        activity: "Visit Horanadu Temple for darshan and lunch (either prasadam or at a nearby hotel – self-sponsored)",
      },
      { time: "02:30 – 04:30 PM", activity: "Explore Soormane Falls" },
      { time: "05:30 PM", activity: "Stop by Hanging Bridge in Kalasa" },
      { time: "07:00 PM", activity: "Return to homestay, have dinner, and rest" },
      { time: "Day 2 – Trek to Bandaje Falls & Ballalarayana Durga Fort", activity: "" },
      { time: "05:30 AM", activity: "Wake-up call" },
      { time: "06:00 – 07:30 AM", activity: "Freshen up, breakfast, and collect packed lunch" },
      { time: "07:30 – 09:00 AM", activity: "Travel to trek starting point (by jeep or bus)" },
      { time: "09:00 – 12:30 PM", activity: "Trek to Bandaje Falls (approx. 3.5 hours)" },
      { time: "12:30 – 01:00 PM", activity: "Lunch break at the falls" },
      { time: "01:30 – 02:00 PM", activity: "Short trek to Ballalarayana Durga Fort" },
      { time: "02:00 – 03:00 PM", activity: "Enjoy the fort views and surroundings" },
      { time: "03:00 – 06:00 PM", activity: "Trek down to the basecamp" },
      { time: "06:00 – 06:30 PM", activity: "Tea and snacks at the homestay" },
      { time: "08:00 PM", activity: "Depart for Bangalore" },
    ],
    included: [
      "Non-A/C round-trip transport from Bangalore",
      "2 Breakfasts, 1 Packed lunch, and 1 Veg dinner",
      "All required permits and entry fees",
      "Dormitory accommodation (separate for men and women)",
      "Abhi Trip trek coordinator",
      "Basic first aid kit",
    ],
    excluded: [
      "Optional Activities",
      "Personal Expenses: Snacks, Bottled Water, Additional Meals",
      "Insurance of any kind",
      "Anything not listed in the 'Inclusions'",
    ],
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    faqs: [
      {
        question: "How difficult is the Bandaje Falls trek?",
        answer: "This is a moderate level trek taking approximately 3.5 hours. Basic fitness level is required.",
      },
      {
        question: "Can we swim at Bandaje Falls?",
        answer:
          "Yes, you can take a refreshing dip at the falls, but please exercise caution and swim at your own risk.",
      },
    ],
    pickupPoints: [
      "Banashankari bus stop - 08:00 PM",
      "Ragigudda Metro Station - 08:15 PM",
      "Silk Board - 08:30 PM",
      "Koramangala - 08:45 PM",
      "Domlur - 09:00 PM",
      "MG Road - 09:15 PM",
      "KTM Mekhri Circle - 09:30 PM",
      "Yeshwanthpura - 09:45 PM",
      "Goraguntepalya - 10:00 PM",
    ],
    cancellationPolicy: "Free cancellation up to 48 hours before departure.",
    thingsToCarry: [
      "Xerox Copy of your Aadhar/Voter ID",
      "Small backpack",
      "Water bottles (1–2 liters)",
      "Comfortable trekking shoes with good grip",
      "Raincoat and bag covers",
      "Extra pair of clothes",
      "Torch or Headlamp",
      "Personal medication",
      "Hand sanitizers",
      "Portable chargers",
      "Chocolates, energy bars, dry fruits",
      "Snacks",
    ],
  },
  {
    id: 106,
    title: "Ooty Adventure",
    description:
      "Experience the magic of misty hills, cascading waterfalls, and scenic landscapes – your ideal weekend getaway to Ooty!",
    detailedDescription:
      "Experience the magic of misty hills, cascading waterfalls, and scenic landscapes – your ideal weekend getaway to Ooty! Discover the Queen of Hill Stations with its colonial charm, tea gardens, and pleasant climate.",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/OOTY%20Two%20Day%20trek.jpg-jtMlm9MWgEY9cSrgNtJcEUvDZu9kJ3.jpeg",
    price: "₹5,500",
    originalPrice: "₹6,000",
    duration: "2 Days / 1 Night",
    difficulty: "Easy",
    groupSize: "20-25",
    rating: 4.5,
    reviews: 112,
    slug: "ooty-adventure",
    highlights: [
      "Needle Rock View Point",
      "Ooty Lake and nearby attractions",
      "Dodda Betta Tea Factory",
      "Pine Tree Forest",
      "Coonoor",
    ],
    location: "270km from Bangalore",
    category: "two-day",
    itinerary: [
      { time: "Day 0 – 10:00 PM", activity: "Begin Your Scenic Journey to Ooty" },
      { time: "10:00 PM", activity: "Start from Banashankari" },
      { time: "10:15 PM", activity: "Quick pickup BTM Layout" },
      { time: "10:30 PM", activity: "Next stop, Silk Board" },
      { time: "10:45 PM", activity: "Board at Bellandur" },
      { time: "11:00 PM", activity: "Assemble at Marathalli" },
      { time: "11:30 PM", activity: "Pickup at Tin Factory" },
      { time: "12:00 AM", activity: "Picking up at Indira Nagar" },
      { time: "12:10 AM", activity: "Meet us at Halasuru" },
      { time: "12:30 AM", activity: "Join at Corporation Circle" },
      { time: "12:50 AM", activity: "Board at Mysuru Road Bus Station" },
      { time: "Day 1 – Into the Wild & Water", activity: "" },
      { time: "7:00 – 10:00 AM", activity: "Arrive and explore Needle Rock View Point" },
      { time: "10:00 AM", activity: "Check-in at your accommodation" },
      { time: "11:30 – 12:30 PM", activity: "Visit Ooty Lake for scenic views and optional boat rides" },
      { time: "1:00 – 2:00 PM", activity: "Lunch at a local restaurant" },
      { time: "2:00 – 3:00 PM", activity: "Explore Dodda Betta Tea Factory" },
      { time: "3:00 – 5:00 PM", activity: "Optional adventure activities" },
      { time: "5:00 – 7:00 PM", activity: "Stroll through Ooty Botanical Garden" },
      { time: "7:00 PM", activity: "Return to stay and unwind" },
      { time: "Day 2 – Discover the Charm of Ooty", activity: "" },
      { time: "9:30 AM", activity: "Check out from the accommodation" },
      { time: "10:00 – 11:00 AM", activity: "Stroll through the scenic Rose Garden" },
      { time: "11:30 – 12:30 PM", activity: "Trek to Doddabetta Peak, the highest point in the Nilgiris" },
      { time: "1:00 – 2:00 PM", activity: "Lunch at a local restaurant (self-sponsored)" },
      { time: "2:00 – 3:00 PM", activity: "Explore the peaceful Pine Tree Forest" },
      { time: "3:00 – 4:00 PM", activity: "Visit 6th Mile Shooting Point for panoramic views" },
      { time: "4:00 PM", activity: "Depart from Ooty to Bangalore" },
      { time: "12:00 AM", activity: "Arrive in Bengaluru" },
    ],
    included: [
      "Non-A/C round-trip transport from Bangalore",
      "2 Breakfasts and 1 Veg dinner",
      "All required permits and entry fees",
      "Dormitory accommodation (separate for men and women)",
      "Abhi Trip trek coordinator",
      "Basic first aid kit",
    ],
    excluded: [
      "Optional Activities",
      "Personal Expenses: Snacks, Bottled Water, Additional Meals",
      "Insurance of any kind",
      "Anything not listed in the 'Inclusions'",
    ],
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/OOTY%20Two%20Day%20trek.jpg-jtMlm9MWgEY9cSrgNtJcEUvDZu9kJ3.jpeg",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    faqs: [
      {
        question: "What is the best time to visit Ooty?",
        answer:
          "October to June is the best time to visit Ooty when the weather is pleasant and ideal for sightseeing.",
      },
      {
        question: "Are boat rides at Ooty Lake included?",
        answer: "Boat rides at Ooty Lake are optional and require additional payment.",
      },
    ],
    pickupPoints: [
      "Banashankari - 10:00 PM",
      "BTM Layout - 10:15 PM",
      "Silk Board - 10:30 PM",
      "Bellandur - 10:45 PM",
      "Marathalli - 11:00 PM",
      "Tin Factory - 11:30 PM",
      "Indira Nagar - 12:00 AM",
      "Halasuru - 12:10 AM",
      "Corporation Circle - 12:30 AM",
      "Mysuru Road Bus Station - 12:50 AM",
    ],
    cancellationPolicy: "Free cancellation up to 48 hours before departure.",
    thingsToCarry: [
      "Xerox Copy of your Aadhar/Voter ID",
      "Small backpack",
      "Water bottles (1–2 liters)",
      "Comfortable trekking shoes with good grip",
      "Raincoat and bag covers",
      "Extra pair of clothes",
      "Torch or Headlamp",
      "Personal medication",
      "Hand sanitizers",
      "Portable chargers",
      "Chocolates, energy bars, dry fruits",
      "Snacks",
    ],
  },
  {
    id: 107,
    title: "Kudremukh Trek",
    description:
      "Kudremukh Trek is a breathtaking journey through rolling hills, dense forests, and mist-covered valleys in the Western Ghats. Known for its iconic horse-face peak, it offers a perfect blend of adventure and natural beauty.",
    detailedDescription:
      "Kudremukh Trek is a breathtaking journey through rolling hills, dense forests, and mist-covered valleys in the Western Ghats. Known for its iconic horse-face peak, it offers a perfect blend of adventure and natural beauty. Experience one of Karnataka's most popular and scenic treks.",
    image: "/placeholder.svg?height=300&width=400",
    price: "₹3,899",
    originalPrice: "₹4,399",
    duration: "2 Days / 1 Night",
    difficulty: "Moderate",
    groupSize: "12-15",
    rating: 4.9,
    reviews: 83,
    slug: "kudremukh-trek",
    highlights: [
      "Kudremukha Peak Trek",
      "Samse Tea Estate",
      "Horanadu Temple",
      "Soormane Falls",
      "Kalasa Hanging Bridge",
    ],
    location: "335km from Bangalore",
    category: "two-day",
    itinerary: [
      { time: "Day 0 – 08:00 PM", activity: "Begin Your Scenic Journey to the Kudremukh Trek" },
      { time: "08:00 PM", activity: "Start from Banashankari bus stop" },
      { time: "08:15 PM", activity: "Join from BTM Layout" },
      { time: "08:30 PM", activity: "Next stop, Silk Board" },
      { time: "08:45 PM", activity: "Assemble at Koramangala" },
      { time: "09:00 PM", activity: "Picking up at Domlur" },
      { time: "09:15 PM", activity: "Meet us at MG Road" },
      { time: "09:30 PM", activity: "Join at KTM Mekhri Circle" },
      { time: "09:45 PM", activity: "Board at Yeshwanthpura" },
      { time: "10:00 PM", activity: "Last pickup at Goraguntepalya" },
      { time: "Day 1 – Kudremukha Trek Adventure", activity: "" },
      { time: "6:00 AM", activity: "Arrive at the homestay and freshen up" },
      { time: "6:30 AM", activity: "Enjoy breakfast and collect your packed lunch" },
      { time: "7:30 AM", activity: "Head out by jeep to the Kudremukha trek starting point" },
      { time: "9:00 AM", activity: "Begin the scenic trek through forest trails" },
      { time: "1:30 PM", activity: "Break at the peak for lunch with a view" },
      { time: "2:30 PM", activity: "Start the descent back to base" },
      { time: "6:00 PM", activity: "Return to the homestay for dinner and well-earned rest" },
      { time: "Day 2 – Nature & Spiritual Exploration", activity: "" },
      { time: "7:00 AM", activity: "Freshen up and have breakfast" },
      { time: "9:00 AM", activity: "Visit the tranquil Samse Tea Estate" },
      {
        time: "10:30 AM",
        activity: "Head to Horanadu Temple for darshan and lunch (prasad or nearby hotel – self-sponsored)",
      },
      { time: "2:30 PM", activity: "Visit the serene Soormane Falls (jeep ride self-sponsored)" },
      { time: "5:30 PM", activity: "Stop at the Hanging Bridge in Kalasa" },
      { time: "8:00 PM", activity: "Depart for Bangalore" },
      { time: "5:30 AM (Next Day)", activity: "Arrive in Bangalore at your designated drop-off point" },
    ],
    included: [
      "Non-A/C round-trip transport from Bangalore",
      "2 Breakfasts, 1 Packed lunch, and 1 Veg dinner",
      "All required permits and entry fees",
      "Dormitory accommodation (separate for men and women)",
      "Abhi Trip trek coordinator",
      "Basic first aid kit",
    ],
    excluded: [
      "Optional Activities",
      "Personal Expenses: Snacks, Bottled Water, Additional Meals",
      "Insurance of any kind",
      "Anything not listed in the 'Inclusions'",
    ],
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    faqs: [
      {
        question: "What is the difficulty level of Kudremukh trek?",
        answer:
          "This is a moderate level trek requiring good fitness levels. The trek involves steep climbs and can be challenging.",
      },
      {
        question: "Is the jeep ride to the starting point included?",
        answer: "Yes, the jeep ride to the Kudremukh trek starting point is included in the package.",
      },
    ],
    pickupPoints: [
      "Banashankari bus stop - 08:00 PM",
      "BTM Layout - 08:15 PM",
      "Silk Board - 08:30 PM",
      "Koramangala - 08:45 PM",
      "Domlur - 09:00 PM",
      "MG Road - 09:15 PM",
      "KTM Mekhri Circle - 09:30 PM",
      "Yeshwanthpura - 09:45 PM",
      "Goraguntepalya - 10:00 PM",
    ],
    cancellationPolicy: "Free cancellation up to 48 hours before departure.",
    thingsToCarry: [
      "Xerox Copy of your Aadhar/Voter ID",
      "Small backpack",
      "Water bottles (1–2 liters)",
      "Comfortable trekking shoes with good grip",
      "Raincoat and bag covers",
      "Extra pair of clothes",
      "Torch or Headlamp",
      "Personal medication",
      "Hand sanitizers",
      "Portable chargers",
      "Chocolates, energy bars, dry fruits",
      "Snacks",
    ],
  },
  {
    id: 108,
    title: "Wayanad Adventure",
    description:
      "Wayanad is a lush green haven in Kerala, known for its misty hills, waterfalls, and wildlife. From scenic treks to ancient caves and spice plantations, it offers a perfect mix of nature and culture. An ideal getaway for adventure seekers and peace lovers alike, Wayanad never disappoints.",
    detailedDescription:
      "Wayanad is a lush green haven in Kerala, known for its misty hills, waterfalls, and wildlife. From scenic treks to ancient caves and spice plantations, it offers a perfect mix of nature and culture. An ideal getaway for adventure seekers and peace lovers alike, Wayanad never disappoints. Experience the pristine beauty of Kerala's hill station.",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Waynad%20Two%20Day%20trek.jpg-qAdduwcXiVR47cV2HbAkDKVupohd4i.jpeg",
    price: "₹4,999",
    originalPrice: "₹5,499",
    duration: "2 Days / 1 Night",
    difficulty: "Easy",
    groupSize: "15-20",
    rating: 4.7,
    reviews: 92,
    slug: "wayanad-adventure",
    highlights: [
      "Edakkal Caves",
      "Banasura Dam",
      "900 Kandi Bridge",
      "Soochipara Waterfalls",
      "Adventure activities: ziplining, giant swing, sky-cycling",
    ],
    location: "280km from Bangalore",
    category: "two-day",
    itinerary: [
      { time: "Day 0 – 10:00 PM", activity: "Begin Your Scenic Journey to the Wayanad" },
      { time: "10:00 PM", activity: "Start from Banashankari" },
      { time: "10:15 PM", activity: "Quick pickup BTM Layout" },
      { time: "10:30 PM", activity: "Next stop, Silk Board" },
      { time: "10:45 PM", activity: "Board at Bellandur" },
      { time: "11:00 PM", activity: "Assemble at Marathalli" },
      { time: "11:30 PM", activity: "Pickup at Tin Factory" },
      { time: "12:00 AM", activity: "Picking up at Indira Nagar" },
      { time: "12:10 AM", activity: "Meet us at Halasuru" },
      { time: "12:30 AM", activity: "Join at Corporation Circle" },
      { time: "12:50 AM", activity: "Board at Mysuru Road Bus Station" },
      { time: "Day 1 – Zipline Your Way to Happiness", activity: "" },
      { time: "9:00 AM", activity: "Arrive at the homestay, freshen up, and enjoy breakfast" },
      { time: "10:00 AM", activity: "Visit Soochipara Waterfalls and unwind in nature" },
      { time: "01:00 PM", activity: "Lunch Stop" },
      { time: "01:30 PM", activity: "Visit the 900 Kandi Glass Bridge (jeep ride self-sponsored)" },
      {
        time: "4:00 PM",
        activity:
          "Try thrilling activities like ziplining (Wayanad's longest), sky cycling & giant swing (self-sponsored)",
      },
      { time: "6:30 PM", activity: "Return to homestay and enjoy dinner" },
      { time: "Day 2 – Nature, History & Scenic Views", activity: "" },
      { time: "07:00 AM", activity: "Freshen up, have breakfast, check out, and head to Banasura Dam" },
      { time: "10:00 AM", activity: "Explore Banasura Dam (activities self-sponsored)" },
      { time: "12:00 PM", activity: "Travel to Edakkal Caves with lunch en route (self-sponsored)" },
      { time: "01:00 PM", activity: "Lunch Stop" },
      { time: "3:00 PM", activity: "Discover the ancient carvings and stories of Edakkal Caves" },
      { time: "5:00 PM", activity: "Depart for Bengaluru" },
      { time: "11:00 PM", activity: "Reach Bengaluru the drop-off points will be the same as the pick-up points" },
    ],
    included: [
      "Non-A/C round-trip transport from Bangalore",
      "2 Breakfasts and 1 Veg dinner",
      "All required permits and entry fees",
      "Dormitory accommodation (separate for men and women)",
      "Abhi Trip trek coordinator",
      "Basic first aid kit",
    ],
    excluded: [
      "Optional Activities",
      "Personal Expenses: Snacks, Bottled Water, Additional Meals",
      "Insurance of any kind",
      "Anything not listed in the 'Inclusions'",
    ],
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Waynad%20Two%20Day%20trek.jpg-qAdduwcXiVR47cV2HbAkDKVupohd4i.jpeg",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    faqs: [
      {
        question: "Are adventure activities included in the package?",
        answer:
          "Adventure activities like ziplining, sky cycling, and giant swing are optional and require additional payment.",
      },
      {
        question: "What is special about Edakkal Caves?",
        answer:
          "Edakkal Caves feature ancient petroglyphs and carvings that date back to the Neolithic era, making them historically significant.",
      },
    ],
    pickupPoints: [
      "Banashankari - 10:00 PM",
      "BTM Layout - 10:15 PM",
      "Silk Board - 10:30 PM",
      "Bellandur - 10:45 PM",
      "Marathalli - 11:00 PM",
      "Tin Factory - 11:30 PM",
      "Indira Nagar - 12:00 AM",
      "Halasuru - 12:10 AM",
      "Corporation Circle - 12:30 AM",
      "Mysuru Road Bus Station - 12:50 AM",
    ],
    cancellationPolicy: "Free cancellation up to 48 hours before departure.",
    thingsToCarry: [
      "Xerox Copy of your Aadhar/Voter ID",
      "Small backpack",
      "Water bottles (1–2 liters)",
      "Comfortable trekking shoes with good grip",
      "Raincoat and bag covers",
      "Extra pair of clothes",
      "Torch or Headlamp",
      "Personal medication",
      "Hand sanitizers",
      "Portable chargers",
      "Chocolates, energy bars, dry fruits",
      "Snacks",
    ],
  },
  {
    id: 109,
    title: "Dandeli Adventure",
    description:
      "Dandeli is an adventure lover's paradise nestled in the Western Ghats of Karnataka. From thrilling white-water rafting on the Kali River to jungle safaris, ziplining, and kayaking—Dandeli offers non-stop excitement in the heart of nature. It's the perfect weekend getaway for adrenaline junkies and nature enthusiasts alike.",
    detailedDescription:
      "Dandeli is an adventure lover's paradise nestled in the Western Ghats of Karnataka. From thrilling white-water rafting on the Kali River to jungle safaris, ziplining, and kayaking—Dandeli offers non-stop excitement in the heart of nature. It's the perfect weekend getaway for adrenaline junkies and nature enthusiasts alike.",
    image: "/placeholder.svg?height=300&width=400",
    price: "₹4,999",
    originalPrice: "₹5,499",
    duration: "2 Days / 1 Night",
    difficulty: "Moderate",
    groupSize: "15-20",
    rating: 4.8,
    reviews: 104,
    slug: "dandeli-adventure",
    highlights: [
      "Adventure activities: white water rafting, kayaking, zip-lining..etc",
      "The Syntheri Rocks",
      "Nature and wildlife",
      "Ulavi Caves",
    ],
    location: "450km from Bangalore",
    category: "two-day",
    itinerary: [
      { time: "Day 0 – 08:00 PM", activity: "Begin Your Scenic Journey to the Dandeli" },
      { time: "08:00 PM", activity: "Start from Banashankari bus stop" },
      { time: "08:15 PM", activity: "Join from BTM Layout" },
      { time: "08:30 PM", activity: "Next stop, Silk Board" },
      { time: "08:45 PM", activity: "Assemble at Koramangala" },
      { time: "09:00 PM", activity: "Picking up at Domlur" },
      { time: "09:15 PM", activity: "Meet us at MG Road" },
      { time: "09:30 PM", activity: "Join at KTM Mekhri Circle" },
      { time: "09:45 PM", activity: "Board at Yeshwanthpura" },
      { time: "Day 1 – Syntheri Rocks Hike & Adventure Activities", activity: "" },
      { time: "7:00 AM", activity: "Arrive at the campsite, freshen up, have breakfast, and explore the surroundings" },
      {
        time: "9:00 AM",
        activity: "Begin the hike from the campsite to Syntheri Rocks to witness the stunning waterfall views",
      },
      { time: "11:15 AM", activity: "Enjoy the panoramic views from the top of Syntheri Rocks" },
      { time: "11:45 AM", activity: "Begin the return hike to the campsite" },
      { time: "1:30 PM", activity: "Lunch at the campsite" },
      {
        time: "2:00 PM",
        activity: "Head out for an action-packed session of adventure activities and return by evening",
      },
      { time: "6:00 PM", activity: "Unwind around a campfire, share stories, enjoy dinner, and rest for the night" },
      { time: "Day 2 – Ulavi Cave Trek", activity: "" },
      { time: "6:00 AM", activity: "Wake up, explore the area, and have breakfast" },
      { time: "8:00 AM", activity: "Depart to the trek starting point" },
      { time: "10:00 AM", activity: "Begin the scenic trek to Ulavi Caves" },
      { time: "2:00 PM", activity: "Reach the caves, explore, and optionally take a dip in the natural pool" },
      { time: "2:30 PM", activity: "Lunch amidst nature" },
      { time: "3:00 PM", activity: "Start the descent back to the base" },
      { time: "5:00 PM", activity: "Relax with a cup of tea before departure" },
      { time: "6:00 PM", activity: "Board the vehicle back to Bengaluru" },
      { time: "8:30 PM", activity: "Stop for dinner en route" },
    ],
    included: [
      "Non-A/C round-trip transport from Bangalore",
      "2 Breakfasts and 1 dinner (Veg and Non Veg)",
      "River Rafting",
      "Swimming in Kali river",
      "Indoor Games (Carom, Archery, Cycling, Badminton, Table tennis)",
      "Dormitory accommodation (separate for men and women)",
      "Abhi Trip trek coordinator",
      "Basic first aid kit",
    ],
    excluded: [
      "Any kind of insurance",
      "Personal Expenses (snacks, mineral water, etc)",
      "Anything not included above",
    ],
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    faqs: [
      {
        question: "Is white water rafting safe for beginners?",
        answer:
          "Yes, white water rafting in Dandeli is safe for beginners. Professional guides and safety equipment are provided.",
      },
      {
        question: "What adventure activities are included?",
        answer:
          "River rafting, swimming in Kali river, and various indoor games are included. Other activities may require additional payment.",
      },
    ],
    pickupPoints: [
      "Banashankari bus stop - 08:00 PM",
      "BTM Layout - 08:15 PM",
      "Silk Board - 08:30 PM",
      "Koramangala - 08:45 PM",
      "Domlur - 09:00 PM",
      "MG Road - 09:15 PM",
      "KTM Mekhri Circle - 09:30 PM",
      "Yeshwanthpura - 09:45 PM",
    ],
    cancellationPolicy: "Free cancellation up to 48 hours before departure.",
    thingsToCarry: [
      "Xerox Copy of your Aadhar/Voter ID",
      "Small backpack",
      "Water bottles (1–2 liters)",
      "Comfortable trekking shoes with good grip",
      "Raincoat and bag covers",
      "Extra pair of clothes",
      "Torch or Headlamp",
      "Personal medication",
      "Hand sanitizers",
      "Portable chargers",
      "Chocolates, energy bars, dry fruits",
      "Snacks",
    ],
  },
]

export function getTripBySlug(slug: string): Trip | undefined {
  return allTrips.find((trip) => trip.slug === slug)
}

export function getOneDayTrips(): Trip[] {
  return allTrips.filter((trip) => trip.category === "one-day")
}

export function getTwoDayTrips(): Trip[] {
  return allTrips.filter((trip) => trip.category === "two-day")
}
